hazelcast:
  map:
    stock:
      map-store:
        enabled: true
        factory-class-name: org.hazelcast.retaildemo.StockMapStoreFactory
        properties:
          connectionUrl: jdbc:postgresql://db:5432/hz-demo
          username: postgres
          password: postgres

