version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hz-demo
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  management-center:
    image: hazelcast/management-center:5.0-BETA-2
    ports:
      - "8080:8080"
    volumes:
      - ./hz-common/target/classes:/opt/classpath
    environment:
      HZ_MC_CLUSTER: dev
      HZ_MC_MEMBERS: hz-member
      MC_CLASSPATH: /opt/classpath
  hz-member:
    image: hazelcast/hazelcast:5.0-BETA-2
    ports:
      - "5701-5800:5701"
    volumes:
      - ./hz-member-config.yaml:/opt/hz-member-config.yaml
      - ./stock-service/target/classes:/opt/hazelcast/ext/stock-service
      - ./hz-common/target/classes:/opt/hazelcast/ext/hz-common
      - /home/erosb/.m2/repository/org/apache/kafka/connect-json/2.2.2/connect-json-2.2.2.jar:/opt/hazelcast/ext/connect-json-2.2.2.jar
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hz-member-config.yaml -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled=true"
      CLASSPATH: "/opt/hazelcast/ext/hz-common:/opt/hazelcast/ext/stock-service:/opt/hazelcast/ext/connect-json-2.2.2.jar"
  stock-service:
    image: openjdk:11
    ports:
      - "8082:8082"
    volumes:
      - ./stock-service/target/stock-service-0.0.1-SNAPSHOT.jar:/opt/stock-service.jar
    entrypoint: "java -jar /opt/stock-service.jar"
    depends_on:
      - kafka
      - hz-member
      - db
      - payment-service
  webshop:
    image: openjdk:11
    ports:
      - "8585:8585"
    volumes:
      - ./webshop/target/webshop-0.0.1-SNAPSHOT.jar:/opt/webshop.jar
    entrypoint: "java -jar /opt/webshop.jar"
    depends_on:
      - kafka
  payment-service:
    image: openjdk:11
    ports:
      - "8081:8081"
    volumes:
      - ./payment-service/target/payment-service-0.0.1-SNAPSHOT.jar:/opt/payment-service.jar
    entrypoint: "java -jar /opt/payment-service.jar"
    depends_on:
      - kafka
